### ISSUE TITLE
Why do you transform the predicted results?

### ISSUE THREAD

**Issue by ReedZyd** [594422814/UDT_pytorch#10]
![image](https://user-images.githubusercontent.com/48706305/66737735-55e82a00-ee9f-11e9-90da-284aded86eb8.png)
Why do you transform it?

**Comment by 594422814** [comment]
We use the shifted Gaussian response map as the pseudo label (as stated in our paper).
We observe that simply using the response map as the pseudo label will significantly enlarge the loss. When the frame number increases, the reconstruction error will be extremely unstable.
