### ISSUE TITLE
Why the mean in training is [109,120,119] and in test is [104,117,123]?

### ISSUE THREAD

**Issue by xxAna** [594422814/UDT_pytorch#11]
Thank you for your share and your excellent work! I am a newer to SOT. I was confused that why the self.mean in dataset.py is [109,120,119] while the net_average_image is [104,117,123] in UDT.py. Is that a superparm?
![image](https://user-images.githubusercontent.com/43401434/67170751-668c2900-f3e6-11e9-96d0-cd994f74da1c.png)
![image](https://user-images.githubusercontent.com/43401434/67170771-786dcc00-f3e6-11e9-8b3b-ae97a18f7ee3.png)

**Comment by 594422814** [comment]
We simply adopt the tracking code from DCFNet, whose online tracking uses a pretrained model by Matconvnet. Therefore, the 'image_mean' value in the tracking code is suitable for the net_param.mat model. 
For your own model, after cropping the training data, you need to compute the image_mean value again and use it for both training and tracking. Please also refer to our baseline DCFNet

**Comment by xxAna** [comment]
@594422814 Thank you for your reply! I still wonder that in this case, does the 'image_mean' value was computed among all training data and apply for both the training and tracking data? What is the motivation for subtracting the 'image_mean' value ? I found it in DCFNet code,but I can't find  the reason why we have to substract such a value both in the DCF and KCF paper. I am a newer and maybe lack some experience. Wish for your reply.Best wishes for you!

**Comment by 594422814** [comment]
This strategy is common in the CNN training (e.g., VGG). This leads to the fast convergence of the model.

**Comment by xxAna** [comment]
@594422814 I got it. Thank you for your patience!
