### ISSUE TITLE
Why the net in training and tracking are different?

### ISSUE THREAD

**Issue by xxAna** [594422814/UDT_pytorch#17]
Thanks for you excellent work and your sharing. When I running your code, I found that the net in track/net.py is set padding=1 in the conv layer of DCFnet while in train/net.py ,there was no padding. Could you please explain that? Waiting for your reply. Best wishes. Thanks you again.

**Comment by 594422814** [comment]
I just follow the settings in DCFNet. 
I also observe similar questions in DCFNet:  https://github.com/foolwood/DCFNet/issues/19
I think this may produce better results? I am not sure.
