### ISSUE TITLE
multiple-object tracking

### ISSUE THREAD

**Issue by Borda** [594422814/UDT_pytorch#4]
Hello, I saw your arxiv paper but the CVPR is not available yet... I would be interested if this unsupervised tracking can handle also multiple object tracking and appearing new object at any time in the video... Thx

**Comment by Borda** [comment]
@594422814 ^^

**Comment by 594422814** [comment]
Hello, sorry for this late response.
Once offline unsupervised trained, this model can be regarded as a normal visual tracker. I think the main challenge using SOT model for MOT lies in the object detection capability, which is not considered in a SOT model. Given a target (bounding box), this method can track it in successive frames, but fails to determine whether it disappears or other new objects appear.
